FROM registry.access.redhat.com/ubi8/dotnet-80:8.0-6 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

COPY . .
user root
RUN dotnet publish "/app/WeatherProject/WeatherProject.csproj" -c Release -o /app/publish
ENTRYPOINT ["dotnet", "/app/publish/WeatherProject.dll"]
